General cog
Sureigh/RemBot pull request #1
Opened 2020-11-16 15:16 UTC by Sureigh

I suck at programming xd
Pls to fix?

2020-11-16 15:18 UTC, Sureigh reviewed
fuck i meant to commit the bot constructor stuff to the to the master branch lmao

2020-11-17 03:42 UTC, XuaTheGrate requested changes
good work!

2020-11-17 03:42 UTC, XuaTheGrate commented on cogs/General.py
> +    async def convert(self, ctx, arg: discord.Message, arg2=None):
```suggestion
    async def convert(self, ctx, message: discord.Message, unit=None):
```

2020-11-17 03:42 UTC, XuaTheGrate commented on cogs/General.py
> +        result = re.search(r"(\d+)(?:[\s*°]?(?:[degrs]?)*)\s?([fc])?", arg.content, flags=re.I)
```suggestion
        result = re.search(r"(\d+)(?:[\s*°]?(?:[degrs]?)*)\s?([fc])?", message.content, flags=re.I)
```

2020-11-17 03:42 UTC, XuaTheGrate commented on cogs/General.py
> +            ctx.send("Error: No match found.")
```suggestion
            await ctx.send("Error: No match found.")
```

2020-11-17 03:42 UTC, XuaTheGrate commented on cogs/General.py
> +                ctx.send(f"{temp}°C is roughly {round((temp * 1.8 + 32), 1)}°F.")
```suggestion
                await ctx.send(f"{temp}°C is roughly {round((temp * 1.8 + 32), 1)}°F.")
```

2020-11-17 03:42 UTC, XuaTheGrate commented on cogs/General.py
> +                ctx.send(f"{temp}°F is roughly {round(((temp - 32) / 1.8), 1)}°C.")
```suggestion
                await ctx.send(f"{temp}°F is roughly {round(((temp - 32) / 1.8), 1)}°C.")
```

2020-11-17 05:18 UTC, merged